export const COPY = {
  uneg: "U.N.E.G",
  sistemaDeInformacionDeFinanzas: "SISTEMA DE INFORMACION DE FINANZAS",
  registroDeAranceles: "REGISTRO DE ARANCELES",
  sif404p: "SIF404P",
  numeroRecibo: "Numero Recibo",
  codigoCaja: "Codigo Caja",
  nombre: "Nombre",
  fechaRecibo: "Fecha Recibo",
  cedula: "Cedula",

  linea: "Linea",
  concepto: "Concepto",
  cantidad: "Cantidad",
  monto: "Monto",

  formaPago: "Forma Pago",
  efectivo: "Efectivo",
  deposito: "Deposito",
  nroDeposito: "Nro. Deposito",
  estado: "Estado",
  motivoDeAnulacion: "Motivo de Anulacion",
  activo: "Activo",
  cerrado: "Cerrado",
  anulado: "Anulado",
  total: "Total",
  banco: "Banco",
  fechaDep: "Fecha Dep.",

  opciones: "OPCIONES",
  registrar: "Registrar",
  descripcionDeRegistrar: "Ingresar nuevos Recibos de Aranceles",
  consultar: "Consultar",
  descripcionDeConsultar:
    "Muestra informacion referente a un Recibo de Arancel",
  pagSig: "Pag sig",
  descripcionDePagSig: "Muestra pagina siguiente de la consulta anterior",
  pagAnt: "paG ant",
  descripcionDePagAnt: "Muestra pagina anterior de la consulta anterior",
  anular: "Anular",
  descripcionDeAnular: "Anula un Recibo de Arancel",
  imprimir: "Imprimir",
  descripcionDeImprimir: "Imprime un Recibo de Arancel",
  transferir: "Transferir",
  descripcionDeTransferir: "Establece enlace con la pantalla requerida",
  limpiar: "Limpiar",
  descripcionDeLimpiar: "Limpia todos los campos de la pantalla",
  retornarRetornar: "retOrnarretOrnar",
  descripcionDeRetornarRetornar: "Regresa al menu anterior inmediato",
  salir: "Salir",
  descripcionDeSalir: "Regresa a la pantalla de ingreso al sistema",
};
